export const LOGIN_USERNAME = 'LOGIN_USERNAME';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';

export const POST_USERNAME_AND_PASSWORD_REQUEST = 'POST_USERNAME_AND_PASSWORD_REQUEST';
export const POST_USERNAME_AND_PASSWORD_REQUEST_FAILURE = 'POST_USERNAME_AND_PASSWORD_REQUEST_FAILURE';
export const SIGNUP = 'SIGNUP';
export const CREATE_USER = 'CREATE_USER';
export const POST_CREATE_USER_SUCCESS = 'POST_CREATE_USER_SUCCESS';
export const POST_CREATE_USER_FAILURE = 'POST_CREATE_USER_FAILURE';
export const GET_ART = 'GET_ART';
export const POST_GET_ART_SUCCESS = 'POST_GET_ART_SUCCESS';
export const POST_GET_ART_FAILURE = 'POST_GET_ART_FAILURE';

