export const LOGIN_USERNAME = 'LOGIN_USERNAME';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';
export const SIGNUP_FIRSTNAME = 'SIGNUP_FIRSTNAME';
export const SIGNUP_LASTNAME = 'SIGNUP_LASTNAME';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const SIGNUP_LONGITUDE = 'SIGNUP_LONGITUDE';
export const SIGNUP_LATITUDE = 'SIGNUP_LATITUDE';
export const SIGNUP_BIO = 'SIGNUP_BIO';

export const POST_USERNAME_AND_PASSWORD_SUCCESS = 'POST_USERNAME_AND_PASSWORD_SUCCESS';
export const POST_USERNAME_AND_PASSWORD_FAILURE = 'POST_USERNAME_AND_PASSWORD_FAILURE';
export const SIGNUP = 'SIGNUP';
export const CREATE_USER = 'CREATE_USER';
export const POST_CREATE_USER_SUCCESS = 'POST_CREATE_USER_SUCCESS';
export const POST_CREATE_USER_FAILURE = 'POST_CREATE_USER_FAILURE';
export const GET_ART = 'GET_ART';
export const POST_GET_ART_SUCCESS = 'POST_GET_ART_SUCCESS';
export const POST_GET_ART_FAILURE = 'POST_GET_ART_FAILURE';

