export const LOGIN_USERNAME = 'LOGIN_USERNAME';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';
export const SIGNUP_FIRSTNAME = 'SIGNUP_FIRSTNAME';
export const SIGNUP_LASTNAME = 'SIGNUP_LASTNAME';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const SIGNUP_LONGITUDE = 'SIGNUP_LONGITUDE';
export const SIGNUP_LATITUDE = 'SIGNUP_LATITUDE';
export const SIGNUP_BIO = 'SIGNUP_BIO';
export const UPDATE_DISTANCE = 'UPDATE_DISTANCE';


export const POST_USERNAME_AND_PASSWORD_REQUEST = 'POST_USERNAME_AND_PASSWORD_REQUEST';
export const POST_USERNAME_AND_PASSWORD_REQUEST_FAILURE = 'POST_USERNAME_AND_PASSWORD_REQUEST_FAILURE';
export const SIGNUP = 'SIGNUP';
export const CREATE_USER = 'CREATE_USER';
export const POST_CREATE_USER_SUCCESS = 'POST_CREATE_USER_SUCCESS';
export const POST_CREATE_USER_FAILURE = 'POST_CREATE_USER_FAILURE';
export const GET_ART = 'GET_ART';
export const POST_GET_ART_SUCCESS = 'POST_GET_ART_SUCCESS';
export const POST_GET_ART_FAILURE = 'POST_GET_ART_FAILURE';

export const CLEAR_STATE_ON_LOGOUT = 'CLEAR_STATE_ON_LOGOUT';


